name: Deployment

on:
    push:
        branches: [main]

jobs:
        deploy:
            name: Deploy
            runs-on: ubuntu-latest
            timeout-minutes: 30

            steps:
               - name: Set up Go
                 uses: actions/setup-go@v5
                 with:
                    go-version: "1.24.1"
                 
               - name: Check out Repository and Submodules
                 uses: actions/checkout@v4

               - name: Build the binary
                 run: ./scripts/buildprod.sh